#!/usr/bin/env python3
"""
gitlab_mr.py — Create a GitLab Merge Request when WOPR issues CAUTION (on_caution hook).

When WOPR is not fully confident, instead of deploying silently, this hook
opens an MR so a human can review before merging to the target branch.

The MR description includes WOPR's reasoning (from JOSHUA_REVERT_FINDINGS_FILE
or JOSHUA_CAUTION_FINDINGS_FILE) so the reviewer has full context.

Usage (called automatically by joshua on_caution hook):
    python3 gitlab_mr.py \
        --gitlab-url https://git.redegal.net \
        --project-id jorge.vazquez/redegal-mecano \
        --source-branch main \
        --target-branch prod

Env vars:
    GITLAB_TOKEN                  GitLab personal access token
    JOSHUA_CYCLE                  Current cycle number
    JOSHUA_PROJECT                Project name
    JOSHUA_CAUTION_FINDINGS_FILE  Path to file with WOPR's reasoning (optional)
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
import urllib.parse
from datetime import datetime
from pathlib import Path


def create_mr(gitlab_url: str, token: str, project_id: str,
              source: str, target: str, title: str, description: str) -> dict | None:
    """Create a GitLab MR via REST API."""
    # URL-encode project_id (handles namespace/repo format)
    encoded_id = urllib.parse.quote(project_id, safe="")
    url = f"{gitlab_url.rstrip('/')}/api/v4/projects/{encoded_id}/merge_requests"

    payload = json.dumps({
        "source_branch": source,
        "target_branch": target,
        "title": title,
        "description": description,
        "labels": "wopr-caution,needs-review",
        "remove_source_branch": False,
    }).encode()

    req = urllib.request.Request(url, data=payload, headers={
        "Content-Type": "application/json",
        "PRIVATE-TOKEN": token,
    })

    try:
        resp = urllib.request.urlopen(req, timeout=15)
        data = json.loads(resp.read())
        return data
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        # MR already exists is not an error
        if e.code == 409 or "already exists" in body.lower():
            print(f"[gitlab_mr] MR already exists between {source} → {target}")
            return {"web_url": "(existing MR)", "iid": "?"}
        print(f"[gitlab_mr] HTTP {e.code}: {body[:300]}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"[gitlab_mr] ERROR: {e}", file=sys.stderr)
        return None


def main():
    cycle = int(os.getenv("JOSHUA_CYCLE", "0"))
    project = os.getenv("JOSHUA_PROJECT", "project")
    findings_file = os.getenv("JOSHUA_CAUTION_FINDINGS_FILE",
                              os.getenv("JOSHUA_REVERT_FINDINGS_FILE", ""))

    p = argparse.ArgumentParser(description="Open GitLab MR on WOPR CAUTION")
    p.add_argument("--gitlab-url",    default=os.getenv("GITLAB_URL", "https://git.redegal.net"))
    p.add_argument("--project-id",    required=True, help="GitLab project path (e.g. jorge.vazquez/redegal-mecano)")
    p.add_argument("--source-branch", default="main",   help="Branch with changes")
    p.add_argument("--target-branch", default="prod",   help="Target branch for MR")
    args = p.parse_args()

    token = os.getenv("GITLAB_TOKEN", "")
    if not token:
        print("[gitlab_mr] GITLAB_TOKEN env var not set", file=sys.stderr)
        sys.exit(1)

    # Read WOPR's reasoning
    findings = ""
    if findings_file and Path(findings_file).exists():
        findings = Path(findings_file).read_text().strip()[:3000]

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    title = f"[WOPR CAUTION] {project} — cycle {cycle} needs review ({timestamp})"

    description = f"""## WOPR issued CAUTION on cycle {cycle}

**Project:** {project}
**Cycle:** {cycle}
**Timestamp:** {timestamp}
**Verdict:** CAUTION — changes deployed but flagged for manual review

---

## WOPR Reasoning

"""
    if findings:
        description += f"```\n{findings}\n```\n"
    else:
        description += "_No detailed reasoning captured. Check sprint logs._\n"

    description += """
---

## Review Checklist

- [ ] Check WOPR's reasoning above
- [ ] Verify no regressions in affected areas
- [ ] Confirm WCAG contrast is maintained
- [ ] Confirm no secrets or credentials introduced
- [ ] Approve or request changes

> Auto-generated by joshua-agent on_caution hook
"""

    print(f"[gitlab_mr] Opening MR: {args.source_branch} → {args.target_branch} in {args.project_id}")
    mr = create_mr(args.gitlab_url, token, args.project_id,
                   args.source_branch, args.target_branch, title, description)

    if not mr:
        print("[gitlab_mr] Failed to create MR", file=sys.stderr)
        sys.exit(1)

    print(f"[gitlab_mr] MR created: {mr.get('web_url', '?')} (#{mr.get('iid', '?')})")


if __name__ == "__main__":
    main()
